export interface TechStack {
  id: string;
  label: string;
  icon: string;
  variants: string[];
}

export interface TechCategory {
  type: string;
  label: string;
  color: string;
  techStacks: TechStack[];
}

export const CUSTOM_ICONS: Record<string, string> = {
  activemq: '/logos/activemq.png',
  zeromq: '/logos/zeromq.png',
  '8thwall': '/logos/8thwall.svg',
};

export const TECH_CATEGORIES: TechCategory[] = [
  {
    type: 'language',
    label: 'Language',
    color: 'from-pink-500 to-rose-500',
    techStacks: [
      { id: 'apex', label: 'Apex', icon: 'apex', variants: ['original'] },
      { id: 'apl', label: 'Apl', icon: 'apl', variants: ['plain'] },
      { id: 'awk', label: 'Awk', icon: 'awk', variants: ['plain-wordmark'] },
      {
        id: 'ballerina',
        label: 'Ballerina',
        icon: 'ballerina',
        variants: ['original', 'original-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'bash', label: 'Bash', icon: 'bash', variants: ['plain'] },
      { id: 'c', label: 'C', icon: 'c', variants: ['original', 'line'] },
      { id: 'cairo', label: 'Cairo', icon: 'cairo', variants: ['plain', 'plain-wordmark'] },
      { id: 'carbon', label: 'Carbon', icon: 'carbon', variants: ['original'] },
      { id: 'ceylon', label: 'Ceylon', icon: 'ceylon', variants: ['plain', 'plain-wordmark'] },
      { id: 'clojure', label: 'Clojure', icon: 'clojure', variants: ['line', 'plain'] },
      { id: 'clojurescript', label: 'Clojurescript', icon: 'clojurescript', variants: ['plain'] },
      { id: 'cobol', label: 'Cobol', icon: 'cobol', variants: ['original'] },
      {
        id: 'coffeescript',
        label: 'Coffeescript',
        icon: 'coffeescript',
        variants: ['original', 'original-wordmark'],
      },
      { id: 'cplusplus', label: 'Cplusplus', icon: 'cplusplus', variants: ['plain', 'line'] },
      {
        id: 'crystal',
        label: 'Crystal',
        icon: 'crystal',
        variants: ['original', 'original-wordmark', 'line', 'line-wordmark'],
      },
      {
        id: 'csharp',
        label: 'Csharp',
        icon: 'csharp',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'dart', label: 'Dart', icon: 'dart', variants: ['plain', 'plain-wordmark'] },
      { id: 'delphi', label: 'Delphi', icon: 'delphi', variants: ['plain'] },
      { id: 'dyalog', label: 'Dyalog', icon: 'dyalog', variants: ['plain'] },
      { id: 'elixir', label: 'Elixir', icon: 'elixir', variants: ['plain', 'plain-wordmark'] },
      { id: 'elm', label: 'Elm', icon: 'elm', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'embeddedc',
        label: 'Embeddedc',
        icon: 'embeddedc',
        variants: ['plain', 'plain-wordmark'],
      },
      { id: 'erlang', label: 'Erlang', icon: 'erlang', variants: ['plain', 'plain-wordmark'] },
      { id: 'fortran', label: 'Fortran', icon: 'fortran', variants: ['original'] },
      { id: 'fsharp', label: 'Fsharp', icon: 'fsharp', variants: ['plain'] },
      { id: 'gleam', label: 'Gleam', icon: 'gleam', variants: ['plain'] },
      { id: 'go', label: 'Go', icon: 'go', variants: ['original-wordmark', 'plain', 'line'] },
      { id: 'groovy', label: 'Groovy', icon: 'groovy', variants: ['plain'] },
      { id: 'haskell', label: 'Haskell', icon: 'haskell', variants: ['plain', 'plain-wordmark'] },
      { id: 'haxe', label: 'Haxe', icon: 'haxe', variants: ['plain'] },
      { id: 'java', label: 'Java', icon: 'java', variants: ['plain', 'plain-wordmark'] },
      { id: 'javascript', label: 'Javascript', icon: 'javascript', variants: ['plain'] },
      { id: 'jule', label: 'Jule', icon: 'jule', variants: ['original', 'original-wordmark'] },
      { id: 'julia', label: 'Julia', icon: 'julia', variants: ['plain', 'plain-wordmark'] },
      { id: 'kotlin', label: 'Kotlin', icon: 'kotlin', variants: ['plain', 'plain-wordmark'] },
      { id: 'labview', label: 'Labview', icon: 'labview', variants: ['plain', 'plain-wordmark'] },
      { id: 'llvm', label: 'Llvm', icon: 'llvm', variants: ['plain', 'line'] },
      { id: 'lua', label: 'Lua', icon: 'lua', variants: ['plain', 'line'] },
      { id: 'matlab', label: 'Matlab', icon: 'matlab', variants: ['plain', 'line'] },
      {
        id: 'nim',
        label: 'Nim',
        icon: 'nim',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'objectivec', label: 'Objectivec', icon: 'objectivec', variants: ['plain'] },
      { id: 'ocaml', label: 'Ocaml', icon: 'ocaml', variants: ['plain', 'plain-wordmark'] },
      { id: 'perl', label: 'Perl', icon: 'perl', variants: ['plain'] },
      { id: 'php', label: 'Php', icon: 'php', variants: ['plain'] },
      { id: 'powershell', label: 'Powershell', icon: 'powershell', variants: ['plain'] },
      { id: 'processing', label: 'Processing', icon: 'processing', variants: ['plain', 'line'] },
      { id: 'prolog', label: 'Prolog', icon: 'prolog', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'purescript',
        label: 'Purescript',
        icon: 'purescript',
        variants: ['original', 'original-wordmark'],
      },
      { id: 'python', label: 'Python', icon: 'python', variants: ['plain', 'plain-wordmark'] },
      { id: 'r', label: 'R', icon: 'r', variants: ['plain', 'line'] },
      { id: 'racket', label: 'Racket', icon: 'racket', variants: ['plain', 'line'] },
      { id: 'rexx', label: 'Rexx', icon: 'rexx', variants: ['plain', 'plain-wordmark'] },
      { id: 'ruby', label: 'Ruby', icon: 'ruby', variants: ['plain', 'plain-wordmark'] },
      { id: 'rust', label: 'Rust', icon: 'rust', variants: ['original', 'line'] },
      { id: 'scala', label: 'Scala', icon: 'scala', variants: ['plain', 'plain-wordmark'] },
      { id: 'solidity', label: 'Solidity', icon: 'solidity', variants: ['plain'] },
      { id: 'swift', label: 'Swift', icon: 'swift', variants: ['plain', 'plain-wordmark'] },
      { id: 'typescript', label: 'Typescript', icon: 'typescript', variants: ['plain'] },
      { id: 'vala', label: 'Vala', icon: 'vala', variants: ['plain', 'plain-wordmark'] },
      { id: 'visualbasic', label: 'Visualbasic', icon: 'visualbasic', variants: ['plain', 'line'] },
      { id: 'vyper', label: 'Vyper', icon: 'vyper', variants: ['original', 'original-wordmark'] },
      { id: 'wasm', label: 'Wasm', icon: 'wasm', variants: ['original', 'plain-wordmark'] },
      { id: 'wolfram', label: 'Wolfram', icon: 'wolfram', variants: ['plain', 'plain-wordmark'] },
      { id: 'zig', label: 'Zig', icon: 'zig', variants: ['original', 'plain-wordmark'] },
    ],
  },
  {
    type: 'frontend',
    label: 'Frontend',
    color: 'from-cyan-500 to-blue-500',
    techStacks: [
      {
        id: 'alpinejs',
        label: 'Alpine.js',
        icon: 'alpinejs',
        variants: ['original', 'original-wordmark'],
      },
      { id: 'angular', label: 'Angular', icon: 'angular', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'angularjs',
        label: 'Angular.js',
        icon: 'angularjs',
        variants: ['plain', 'plain-wordmark'],
      },
      {
        id: 'angularmaterial',
        label: 'Angularmaterial',
        icon: 'angularmaterial',
        variants: ['plain'],
      },
      {
        id: 'antdesign',
        label: 'Antdesign',
        icon: 'antdesign',
        variants: ['plain', 'plain-wordmark'],
      },
      { id: 'astro', label: 'Astro', icon: 'astro', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'backbonejs',
        label: 'Backbone.js',
        icon: 'backbonejs',
        variants: ['plain', 'plain-wordmark'],
      },
      {
        id: 'biome',
        label: 'Biome',
        icon: 'biome',
        variants: ['original', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      {
        id: 'bootstrap',
        label: 'Bootstrap',
        icon: 'bootstrap',
        variants: ['plain', 'plain-wordmark'],
      },
      { id: 'bulma', label: 'Bulma', icon: 'bulma', variants: ['plain'] },
      {
        id: 'chakraui',
        label: 'Chakraui',
        icon: 'chakraui',
        variants: ['plain', 'plain-wordmark'],
      },
      { id: 'chartjs', label: 'Chart.js', icon: 'chartjs', variants: ['plain', 'plain-wordmark'] },
      { id: 'clarity', label: 'Clarity', icon: 'clarity', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'corejs',
        label: 'Core.js',
        icon: 'corejs',
        variants: ['original', 'original-wordmark'],
      },
      { id: 'css3', label: 'Css3', icon: 'css3', variants: ['plain', 'plain-wordmark'] },
      { id: 'd3js', label: 'D3.js', icon: 'd3js', variants: ['plain'] },
      { id: 'datatables', label: 'Datatables', icon: 'datatables', variants: ['original'] },
      { id: 'eleventy', label: 'Eleventy', icon: 'eleventy', variants: ['plain'] },
      { id: 'ember', label: 'Ember', icon: 'ember', variants: ['original-wordmark', 'plain'] },
      {
        id: 'eslint',
        label: 'Eslint',
        icon: 'eslint',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      {
        id: 'foundation',
        label: 'Foundation',
        icon: 'foundation',
        variants: ['plain', 'plain-wordmark'],
      },
      {
        id: 'framermotion',
        label: 'Framermotion',
        icon: 'framermotion',
        variants: ['original', 'original-wordmark'],
      },
      {
        id: 'framework7',
        label: 'Framework7',
        icon: 'framework7',
        variants: ['original', 'original-wordmark'],
      },
      { id: 'gatsby', label: 'Gatsby', icon: 'gatsby', variants: ['original', 'plain-wordmark'] },
      {
        id: 'handlebars',
        label: 'Handlebars',
        icon: 'handlebars',
        variants: ['original', 'original-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'html5', label: 'Html5', icon: 'html5', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'htmx',
        label: 'Htmx',
        icon: 'htmx',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      {
        id: 'inertiajs',
        label: 'Inertia.js',
        icon: 'inertiajs',
        variants: ['plain', 'plain-wordmark'],
      },
      { id: 'jeet', label: 'Jeet', icon: 'jeet', variants: ['plain', 'plain-wordmark'] },
      { id: 'jquery', label: 'Jquery', icon: 'jquery', variants: ['plain', 'plain-wordmark'] },
      { id: 'knockout', label: 'Knockout', icon: 'knockout', variants: ['plain-wordmark'] },
      { id: 'less', label: 'Less', icon: 'less', variants: ['plain-wordmark'] },
      {
        id: 'livewire',
        label: 'Livewire',
        icon: 'livewire',
        variants: ['plain-wordmark', 'plain'],
      },
      { id: 'lodash', label: 'Lodash', icon: 'lodash', variants: ['plain'] },
      {
        id: 'materializecss',
        label: 'Materializecss',
        icon: 'materializecss',
        variants: ['plain'],
      },
      { id: 'materialui', label: 'Materialui', icon: 'materialui', variants: ['plain'] },
      { id: 'meteor', label: 'Meteor', icon: 'meteor', variants: ['plain', 'plain-wordmark'] },
      { id: 'mithril', label: 'Mithril', icon: 'mithril', variants: ['original', 'line'] },
      { id: 'mobx', label: 'Mobx', icon: 'mobx', variants: ['plain'] },
      {
        id: 'nextjs',
        label: 'Next.js',
        icon: 'nextjs',
        variants: ['original-wordmark', 'plain', 'line', 'line-wordmark'],
      },
      { id: 'ngrx', label: 'Ngrx', icon: 'ngrx', variants: ['plain'] },
      { id: 'nuxt', label: 'Nuxt', icon: 'nuxt', variants: ['original', 'plain-wordmark'] },
      { id: 'nuxtjs', label: 'Nuxt.js', icon: 'nuxtjs', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'postcss',
        label: 'Postcss',
        icon: 'postcss',
        variants: ['original', 'plain-wordmark'],
      },
      { id: 'primeng', label: 'Primeng', icon: 'primeng', variants: ['plain'] },
      { id: 'pug', label: 'Pug', icon: 'pug', variants: ['plain', 'line'] },
      { id: 'quasar', label: 'Quasar', icon: 'quasar', variants: ['plain-wordmark', 'plain'] },
      { id: 'qwik', label: 'Qwik', icon: 'qwik', variants: ['plain', 'plain-wordmark'] },
      { id: 'reach', label: 'Reach', icon: 'reach', variants: ['plain'] },
      { id: 'react', label: 'React', icon: 'react', variants: ['original', 'original-wordmark'] },
      {
        id: 'reactbootstrap',
        label: 'Reactbootstrap',
        icon: 'reactbootstrap',
        variants: ['original'],
      },
      {
        id: 'reactnavigation',
        label: 'Reactnavigation',
        icon: 'reactnavigation',
        variants: ['original'],
      },
      {
        id: 'reactrouter',
        label: 'Reactrouter',
        icon: 'reactrouter',
        variants: ['plain', 'plain-wordmark'],
      },
      { id: 'rect', label: 'Rect', icon: 'rect', variants: ['plain'] },
      { id: 'redux', label: 'Redux', icon: 'redux', variants: ['original'] },
      { id: 'reflex', label: 'Reflex', icon: 'reflex', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'remix',
        label: 'Remix',
        icon: 'remix',
        variants: ['original', 'original-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'rxjs', label: 'Rx.js', icon: 'rxjs', variants: ['plain'] },
      { id: 'sass', label: 'Sass', icon: 'sass', variants: ['original'] },
      { id: 'solidjs', label: 'Solid.js', icon: 'solidjs', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'stenciljs',
        label: 'Stencil.js',
        icon: 'stenciljs',
        variants: ['plain', 'plain-wordmark'],
      },
      {
        id: 'styledcomponents',
        label: 'Styledcomponents',
        icon: 'styledcomponents',
        variants: ['plain', 'plain-wordmark'],
      },
      { id: 'stylus', label: 'Stylus', icon: 'stylus', variants: ['original'] },
      { id: 'svelte', label: 'Svelte', icon: 'svelte', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'svgo',
        label: 'Svgo',
        icon: 'svgo',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'swiper', label: 'Swiper', icon: 'swiper', variants: ['original'] },
      {
        id: 'tailwindcss',
        label: 'Tailwindcss',
        icon: 'tailwindcss',
        variants: ['original', 'plain-wordmark'],
      },
      {
        id: 'thymeleaf',
        label: 'Thymeleaf',
        icon: 'thymeleaf',
        variants: ['plain', 'plain-wordmark'],
      },
      {
        id: 'veevalidate',
        label: 'Veevalidate',
        icon: 'veevalidate',
        variants: ['original', 'line'],
      },
      {
        id: 'vuejs',
        label: 'Vue.js',
        icon: 'vuejs',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'vuestorefront', label: 'Vuestorefront', icon: 'vuestorefront', variants: ['plain'] },
      { id: 'vuetify', label: 'Vuetify', icon: 'vuetify', variants: ['line', 'plain'] },
      { id: 'waku', label: 'Waku', icon: 'waku', variants: ['plain', 'line'] },
      { id: 'zustand', label: 'Zustand', icon: 'zustand', variants: ['plain'] },
    ],
  },
  {
    type: 'backend',
    label: 'Backend',
    color: 'from-green-500 to-teal-500',
    techStacks: [
      {
        id: 'adonisjs',
        label: 'Adonis.js',
        icon: 'adonisjs',
        variants: ['original', 'original-wordmark'],
      },
      { id: 'akka', label: 'Akka', icon: 'akka', variants: ['plain', 'plain-wordmark'] },
      { id: 'blazor', label: 'Blazor', icon: 'blazor', variants: ['original', 'line'] },
      { id: 'cakephp', label: 'Cakephp', icon: 'cakephp', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'codeigniter',
        label: 'Codeigniter',
        icon: 'codeigniter',
        variants: ['plain', 'plain-wordmark'],
      },
      {
        id: 'contao',
        label: 'Contao',
        icon: 'contao',
        variants: ['original', 'original-wordmark'],
      },
      {
        id: 'denojs',
        label: 'Deno.js',
        icon: 'denojs',
        variants: ['original', 'original-wordmark'],
      },
      { id: 'django', label: 'Django', icon: 'django', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'djangorest',
        label: 'Djangorest',
        icon: 'djangorest',
        variants: ['plain', 'line', 'plain-wordmark', 'line-wordmark'],
      },
      { id: 'dot-net', label: 'Dot Net', icon: 'dot-net', variants: ['plain', 'plain-wordmark'] },
      { id: 'dotnetcore', label: 'Dotnetcore', icon: 'dotnetcore', variants: ['plain'] },
      { id: 'dropwizard', label: 'Dropwizard', icon: 'dropwizard', variants: ['plain'] },
      { id: 'drupal', label: 'Drupal', icon: 'drupal', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'express',
        label: 'Express',
        icon: 'express',
        variants: ['original', 'original-wordmark'],
      },
      { id: 'fastify', label: 'Fastify', icon: 'fastify', variants: ['plain', 'plain-wordmark'] },
      { id: 'feathersjs', label: 'Feathers.js', icon: 'feathersjs', variants: ['original'] },
      { id: 'fiber', label: 'Fiber', icon: 'fiber', variants: ['plain', 'line'] },
      { id: 'filamentphp', label: 'Filamentphp', icon: 'filamentphp', variants: ['original'] },
      { id: 'flask', label: 'Flask', icon: 'flask', variants: ['original', 'original-wordmark'] },
      { id: 'ghost', label: 'Ghost', icon: 'ghost', variants: ['original', 'original-wordmark'] },
      { id: 'grails', label: 'Grails', icon: 'grails', variants: ['plain'] },
      {
        id: 'jhipster',
        label: 'Jhipster',
        icon: 'jhipster',
        variants: ['plain', 'plain-wordmark'],
      },
      {
        id: 'krakenjs',
        label: 'Kraken.js',
        icon: 'krakenjs',
        variants: ['plain', 'plain-wordmark'],
      },
      { id: 'ktor', label: 'Ktor', icon: 'ktor', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'laminas',
        label: 'Laminas',
        icon: 'laminas',
        variants: ['original', 'original-wordmark', 'line', 'line-wordmark'],
      },
      {
        id: 'laravel',
        label: 'Laravel',
        icon: 'laravel',
        variants: ['original', 'original-wordmark', 'line', 'line-wordmark'],
      },
      {
        id: 'laraveljetstream',
        label: 'Laraveljetstream',
        icon: 'laraveljetstream',
        variants: ['original', 'plain-wordmark'],
      },
      { id: 'lumen', label: 'Lumen', icon: 'lumen', variants: ['original'] },
      {
        id: 'magento',
        label: 'Magento',
        icon: 'magento',
        variants: ['original', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'modx', label: 'Modx', icon: 'modx', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'moleculer',
        label: 'Moleculer',
        icon: 'moleculer',
        variants: ['original', 'original-wordmark'],
      },
      { id: 'moodle', label: 'Moodle', icon: 'moodle', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'nestjs',
        label: 'Nest.js',
        icon: 'nestjs',
        variants: ['original', 'original-wordmark', 'line', 'line-wordmark'],
      },
      {
        id: 'nodejs',
        label: 'Node.js',
        icon: 'nodejs',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'nodemon', label: 'Nodemon', icon: 'nodemon', variants: ['plain', 'line'] },
      { id: 'nodered', label: 'Nodered', icon: 'nodered', variants: ['plain', 'line'] },
      {
        id: 'nodewebkit',
        label: 'Nodewebkit',
        icon: 'nodewebkit',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'phalcon', label: 'Phalcon', icon: 'phalcon', variants: ['plain'] },
      {
        id: 'phoenix',
        label: 'Phoenix',
        icon: 'phoenix',
        variants: ['original', 'plain-wordmark'],
      },
      {
        id: 'pm2',
        label: 'Pm2',
        icon: 'pm2',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      {
        id: 'processwire',
        label: 'Processwire',
        icon: 'processwire',
        variants: ['original', 'plain-wordmark'],
      },
      { id: 'quarkus', label: 'Quarkus', icon: 'quarkus', variants: ['plain', 'plain-wordmark'] },
      { id: 'rails', label: 'Rails', icon: 'rails', variants: ['plain', 'plain-wordmark'] },
      { id: 'sanity', label: 'Sanity', icon: 'sanity', variants: ['plain'] },
      {
        id: 'shopware',
        label: 'Shopware',
        icon: 'shopware',
        variants: ['original', 'original-wordmark'],
      },
      {
        id: 'spring',
        label: 'Spring',
        icon: 'spring',
        variants: ['original', 'original-wordmark'],
      },
      {
        id: 'sulu',
        label: 'Sulu',
        icon: 'sulu',
        variants: ['original', 'original-wordmark', 'line', 'line-wordmark'],
      },
      {
        id: 'symfony',
        label: 'Symfony',
        icon: 'symfony',
        variants: ['original', 'original-wordmark'],
      },
      { id: 'tomcat', label: 'Tomcat', icon: 'tomcat', variants: ['line', 'line-wordmark'] },
      {
        id: 'typo3',
        label: 'Typo3',
        icon: 'typo3',
        variants: ['original', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'uwsgi', label: 'Uwsgi', icon: 'uwsgi', variants: ['plain'] },
      { id: 'vaadin', label: 'Vaadin', icon: 'vaadin', variants: ['original'] },
      {
        id: 'vertx',
        label: 'Vertx',
        icon: 'vertx',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'webflow', label: 'Webflow', icon: 'webflow', variants: ['original'] },
      {
        id: 'woocommerce',
        label: 'Woocommerce',
        icon: 'woocommerce',
        variants: ['plain', 'plain-wordmark'],
      },
      {
        id: 'wordpress',
        label: 'Wordpress',
        icon: 'wordpress',
        variants: ['plain', 'plain-wordmark'],
      },
      { id: 'yii', label: 'Yii', icon: 'yii', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'zend',
        label: 'Zend',
        icon: 'zend',
        variants: ['original', 'original-wordmark', 'line', 'line-wordmark'],
      },
    ],
  },
  {
    type: 'database',
    label: 'Database',
    color: 'from-green-500 to-emerald-500',
    techStacks: [
      {
        id: 'aerospike',
        label: 'Aerospike',
        icon: 'aerospike',
        variants: ['original', 'original-wordmark'],
      },
      {
        id: 'azuresqldatabase',
        label: 'Azuresqldatabase',
        icon: 'azuresqldatabase',
        variants: ['plain'],
      },
      {
        id: 'cassandra',
        label: 'Cassandra',
        icon: 'cassandra',
        variants: ['plain', 'plain-wordmark'],
      },
      { id: 'clickhouse', label: 'Clickhouse', icon: 'clickhouse', variants: ['plain'] },
      {
        id: 'cosmosdb',
        label: 'Cosmosdb',
        icon: 'cosmosdb',
        variants: ['plain', 'plain-wordmark'],
      },
      {
        id: 'couchbase',
        label: 'Couchbase',
        icon: 'couchbase',
        variants: ['original', 'plain-wordmark'],
      },
      { id: 'couchdb', label: 'Couchdb', icon: 'couchdb', variants: ['plain', 'plain-wordmark'] },
      { id: 'dbeaver', label: 'Dbeaver', icon: 'dbeaver', variants: ['plain'] },
      {
        id: 'doctrine',
        label: 'Doctrine',
        icon: 'doctrine',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'duckdb', label: 'Duckdb', icon: 'duckdb', variants: ['plain'] },
      { id: 'dynamodb', label: 'Dynamodb', icon: 'dynamodb', variants: ['plain'] },
      { id: 'ecto', label: 'Ecto', icon: 'ecto', variants: ['original', 'plain-wordmark'] },
      {
        id: 'elasticsearch',
        label: 'Elasticsearch',
        icon: 'elasticsearch',
        variants: ['plain-wordmark', 'plain'],
      },
      {
        id: 'faunadb',
        label: 'Faunadb',
        icon: 'faunadb',
        variants: ['original-wordmark', 'original', 'line', 'line-wordmark'],
      },
      { id: 'firebird', label: 'Firebird', icon: 'firebird', variants: ['plain'] },
      {
        id: 'hibernate',
        label: 'Hibernate',
        icon: 'hibernate',
        variants: ['plain', 'plain-wordmark'],
      },
      {
        id: 'influxdb',
        label: 'Influxdb',
        icon: 'influxdb',
        variants: ['original', 'original-wordmark'],
      },
      { id: 'knexjs', label: 'Knex.js', icon: 'knexjs', variants: ['original', 'plain-wordmark'] },
      {
        id: 'liquibase',
        label: 'Liquibase',
        icon: 'liquibase',
        variants: ['original-wordmark', 'original'],
      },
      {
        id: 'mariadb',
        label: 'Mariadb',
        icon: 'mariadb',
        variants: ['original', 'original-wordmark'],
      },
      {
        id: 'memcached',
        label: 'Memcached',
        icon: 'memcached',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      {
        id: 'microsoftsqlserver',
        label: 'Microsoftsqlserver',
        icon: 'microsoftsqlserver',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'mongodb', label: 'Mongodb', icon: 'mongodb', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'mongoose',
        label: 'Mongoose',
        icon: 'mongoose',
        variants: ['original', 'original-wordmark'],
      },
      { id: 'mysql', label: 'Mysql', icon: 'mysql', variants: ['original', 'plain-wordmark'] },
      { id: 'nats', label: 'Nats', icon: 'nats', variants: ['plain'] },
      { id: 'neo4j', label: 'Neo4j', icon: 'neo4j', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'nhibernate',
        label: 'Nhibernate',
        icon: 'nhibernate',
        variants: ['plain-wordmark', 'plain', 'line', 'line-wordmark'],
      },
      { id: 'oracle', label: 'Oracle', icon: 'oracle', variants: ['original'] },
      {
        id: 'postgresql',
        label: 'Postgresql',
        icon: 'postgresql',
        variants: ['plain', 'plain-wordmark'],
      },
      {
        id: 'prisma',
        label: 'Prisma',
        icon: 'prisma',
        variants: ['original', 'original-wordmark'],
      },
      {
        id: 'rabbitmq',
        label: 'Rabbitmq',
        icon: 'rabbitmq',
        variants: ['original', 'plain-wordmark'],
      },
      { id: 'realm', label: 'Realm', icon: 'realm', variants: ['plain', 'plain-wordmark'] },
      { id: 'redis', label: 'Redis', icon: 'redis', variants: ['plain', 'plain-wordmark'] },
      { id: 'rocksdb', label: 'Rocksdb', icon: 'rocksdb', variants: ['plain', 'line'] },
      {
        id: 'sequelize',
        label: 'Sequelize',
        icon: 'sequelize',
        variants: ['plain', 'plain-wordmark'],
      },
      { id: 'spicedb', label: 'Spicedb', icon: 'spicedb', variants: ['plain', 'line'] },
      {
        id: 'sqlalchemy',
        label: 'Sqlalchemy',
        icon: 'sqlalchemy',
        variants: ['plain', 'plain-wordmark'],
      },
      { id: 'sqldeveloper', label: 'Sqldeveloper', icon: 'sqldeveloper', variants: ['plain'] },
      { id: 'sqlite', label: 'Sqlite', icon: 'sqlite', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'surrealdb',
        label: 'Surrealdb',
        icon: 'surrealdb',
        variants: ['plain', 'plain-wordmark'],
      },
      { id: 'vitess', label: 'Vitess', icon: 'vitess', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'yugabytedb',
        label: 'Yugabytedb',
        icon: 'yugabytedb',
        variants: ['plain', 'plain-wordmark'],
      },
    ],
  },
  {
    type: 'cloud',
    label: 'Cloud',
    color: 'from-orange-500 to-red-500',
    techStacks: [
      {
        id: 'amazonwebservices',
        label: 'Amazonwebservices',
        icon: 'amazonwebservices',
        variants: ['plain-wordmark', 'line-wordmark'],
      },
      {
        id: 'appwrite',
        label: 'Appwrite',
        icon: 'appwrite',
        variants: ['original', 'plain-wordmark'],
      },
      { id: 'azure', label: 'Azure', icon: 'azure', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'cloudflare',
        label: 'Cloudflare',
        icon: 'cloudflare',
        variants: ['plain', 'plain-wordmark'],
      },
      {
        id: 'cloudflareworkers',
        label: 'Cloudflareworkers',
        icon: 'cloudflareworkers',
        variants: ['plain', 'plain-wordmark'],
      },
      { id: 'cloudrun', label: 'Cloudrun', icon: 'cloudrun', variants: ['plain', 'line'] },
      {
        id: 'detaspace',
        label: 'Detaspace',
        icon: 'detaspace',
        variants: ['line', 'line-wordmark'],
      },
      {
        id: 'digitalocean',
        label: 'Digitalocean',
        icon: 'digitalocean',
        variants: ['original', 'original-wordmark'],
      },
      {
        id: 'discloud',
        label: 'Discloud',
        icon: 'discloud',
        variants: ['original', 'plain-wordmark'],
      },
      {
        id: 'firebase',
        label: 'Firebase',
        icon: 'firebase',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      {
        id: 'googlecloud',
        label: 'Googlecloud',
        icon: 'googlecloud',
        variants: ['plain', 'plain-wordmark'],
      },
      {
        id: 'harvester',
        label: 'Harvester',
        icon: 'harvester',
        variants: ['original', 'plain-wordmark'],
      },
      {
        id: 'heroku',
        label: 'Heroku',
        icon: 'heroku',
        variants: ['original', 'original-wordmark', 'plain', 'plain-wordmark'],
      },
      { id: 'hyperv', label: 'Hyperv', icon: 'hyperv', variants: ['original-wordmark', 'plain'] },
      { id: 'netlify', label: 'Netlify', icon: 'netlify', variants: ['plain', 'plain-wordmark'] },
      { id: 'nomad', label: 'Nomad', icon: 'nomad', variants: ['original', 'plain-wordmark'] },
      {
        id: 'openstack',
        label: 'Openstack',
        icon: 'openstack',
        variants: ['original', 'plain-wordmark'],
      },
      {
        id: 'portainer',
        label: 'Portainer',
        icon: 'portainer',
        variants: ['original', 'original-wordmark'],
      },
      { id: 'proxmox', label: 'Proxmox', icon: 'proxmox', variants: ['plain', 'plain-wordmark'] },
      { id: 'pulumi', label: 'Pulumi', icon: 'pulumi', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'railway',
        label: 'Railway',
        icon: 'railway',
        variants: ['original', 'original-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'salesforce', label: 'Salesforce', icon: 'salesforce', variants: ['plain'] },
      {
        id: 'scalingo',
        label: 'Scalingo',
        icon: 'scalingo',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      {
        id: 'supabase',
        label: 'Supabase',
        icon: 'supabase',
        variants: ['plain', 'plain-wordmark'],
      },
      { id: 'talos', label: 'Talos', icon: 'talos', variants: ['plain'] },
      {
        id: 'teleport',
        label: 'Teleport',
        icon: 'teleport',
        variants: ['original', 'original-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'vault', label: 'Vault', icon: 'vault', variants: ['original', 'plain-wordmark'] },
      {
        id: 'vercel',
        label: 'Vercel',
        icon: 'vercel',
        variants: ['original', 'original-wordmark', 'line', 'line-wordmark'],
      },
      {
        id: 'vsphere',
        label: 'Vsphere',
        icon: 'vsphere',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
    ],
  },
  {
    type: 'devops',
    label: 'DevOps',
    color: 'from-blue-500 to-indigo-500',
    techStacks: [
      { id: 'ansible', label: 'Ansible', icon: 'ansible', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'apache',
        label: 'Apache',
        icon: 'apache',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      {
        id: 'apacheairflow',
        label: 'Apacheairflow',
        icon: 'apacheairflow',
        variants: ['plain', 'plain-wordmark'],
      },
      {
        id: 'apachekafka',
        label: 'Apachekafka',
        icon: 'apachekafka',
        variants: ['original', 'original-wordmark'],
      },
      { id: 'argocd', label: 'Argocd', icon: 'argocd', variants: ['plain', 'plain-wordmark'] },
      { id: 'azuredevops', label: 'Azuredevops', icon: 'azuredevops', variants: ['plain'] },
      {
        id: 'bamboo',
        label: 'Bamboo',
        icon: 'bamboo',
        variants: ['original', 'original-wordmark'],
      },
      { id: 'beats', label: 'Beats', icon: 'beats', variants: ['plain'] },
      {
        id: 'bitbucket',
        label: 'Bitbucket',
        icon: 'bitbucket',
        variants: ['original', 'original-wordmark'],
      },
      {
        id: 'circleci',
        label: 'Circleci',
        icon: 'circleci',
        variants: ['plain', 'plain-wordmark'],
      },
      { id: 'codeac', label: 'Codeac', icon: 'codeac', variants: ['original'] },
      { id: 'consul', label: 'Consul', icon: 'consul', variants: ['original', 'plain-wordmark'] },
      {
        id: 'cpanel',
        label: 'Cpanel',
        icon: 'cpanel',
        variants: ['original', 'original-wordmark'],
      },
      {
        id: 'datadog',
        label: 'Datadog',
        icon: 'datadog',
        variants: ['original', 'original-wordmark'],
      },
      { id: 'docker', label: 'Docker', icon: 'docker', variants: ['plain', 'plain-wordmark'] },
      { id: 'dovecot', label: 'Dovecot', icon: 'dovecot', variants: ['plain', 'line'] },
      {
        id: 'dynatrace',
        label: 'Dynatrace',
        icon: 'dynatrace',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'envoy', label: 'Envoy', icon: 'envoy', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'filezilla',
        label: 'Filezilla',
        icon: 'filezilla',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      {
        id: 'forgejo',
        label: 'Forgejo',
        icon: 'forgejo',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'gardener', label: 'Gardener', icon: 'gardener', variants: ['plain', 'line'] },
      { id: 'git', label: 'Git', icon: 'git', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'gitbook',
        label: 'Gitbook',
        icon: 'gitbook',
        variants: ['original', 'original-wordmark', 'line', 'line-wordmark'],
      },
      {
        id: 'github',
        label: 'Github',
        icon: 'github',
        variants: ['original', 'original-wordmark'],
      },
      {
        id: 'githubactions',
        label: 'Githubactions',
        icon: 'githubactions',
        variants: ['plain', 'plain-wordmark'],
      },
      {
        id: 'gitkraken',
        label: 'Gitkraken',
        icon: 'gitkraken',
        variants: ['original', 'plain-wordmark'],
      },
      { id: 'gitlab', label: 'Gitlab', icon: 'gitlab', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'grafana',
        label: 'Grafana',
        icon: 'grafana',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      {
        id: 'harbor',
        label: 'Harbor',
        icon: 'harbor',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'helm', label: 'Helm', icon: 'helm', variants: ['original', 'line'] },
      {
        id: 'jaegertracing',
        label: 'Jaegertracing',
        icon: 'jaegertracing',
        variants: ['plain', 'plain-wordmark'],
      },
      { id: 'jenkins', label: 'Jenkins', icon: 'jenkins', variants: ['line', 'plain'] },
      {
        id: 'k3os',
        label: 'K3os',
        icon: 'k3os',
        variants: ['original', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'k3s', label: 'K3s', icon: 'k3s', variants: ['original', 'plain-wordmark'] },
      { id: 'kibana', label: 'Kibana', icon: 'kibana', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'kubeflow',
        label: 'Kubeflow',
        icon: 'kubeflow',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      {
        id: 'kubernetes',
        label: 'Kubernetes',
        icon: 'kubernetes',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      {
        id: 'logstash',
        label: 'Logstash',
        icon: 'logstash',
        variants: ['plain-wordmark', 'plain'],
      },
      {
        id: 'mercurial',
        label: 'Mercurial',
        icon: 'mercurial',
        variants: ['plain', 'plain-wordmark'],
      },
      {
        id: 'netbox',
        label: 'Netbox',
        icon: 'netbox',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'newrelic', label: 'Newrelic', icon: 'newrelic', variants: ['plain', 'line'] },
      { id: 'nginx', label: 'Nginx', icon: 'nginx', variants: ['original'] },
      {
        id: 'opentelemetry',
        label: 'Opentelemetry',
        icon: 'opentelemetry',
        variants: ['plain', 'plain-wordmark'],
      },
      {
        id: 'packer',
        label: 'Packer',
        icon: 'packer',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'podman', label: 'Podman', icon: 'podman', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'prometheus',
        label: 'Prometheus',
        icon: 'prometheus',
        variants: ['original', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'putty', label: 'Putty', icon: 'putty', variants: ['plain'] },
      {
        id: 'rancher',
        label: 'Rancher',
        icon: 'rancher',
        variants: ['original', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      {
        id: 'sentry',
        label: 'Sentry',
        icon: 'sentry',
        variants: ['original', 'original-wordmark'],
      },
      {
        id: 'sonarqube',
        label: 'Sonarqube',
        icon: 'sonarqube',
        variants: ['original', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      {
        id: 'sourcetree',
        label: 'Sourcetree',
        icon: 'sourcetree',
        variants: ['original', 'original-wordmark'],
      },
      { id: 'splunk', label: 'Splunk', icon: 'splunk', variants: ['original-wordmark'] },
      { id: 'ssh', label: 'Ssh', icon: 'ssh', variants: ['original', 'original-wordmark'] },
      {
        id: 'subversion',
        label: 'Subversion',
        icon: 'subversion',
        variants: ['original', 'plain-wordmark'],
      },
      {
        id: 'terraform',
        label: 'Terraform',
        icon: 'terraform',
        variants: ['plain', 'plain-wordmark'],
      },
      {
        id: 'terramate',
        label: 'Terramate',
        icon: 'terramate',
        variants: ['original', 'original-wordmark'],
      },
      { id: 'tmux', label: 'Tmux', icon: 'tmux', variants: ['plain', 'plain-wordmark'] },
      { id: 'tortoisegit', label: 'Tortoisegit', icon: 'tortoisegit', variants: ['plain', 'line'] },
      {
        id: 'towergit',
        label: 'Towergit',
        icon: 'towergit',
        variants: ['plain', 'plain-wordmark'],
      },
      {
        id: 'traefikmesh',
        label: 'Traefikmesh',
        icon: 'traefikmesh',
        variants: ['original', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      {
        id: 'traefikproxy',
        label: 'Traefikproxy',
        icon: 'traefikproxy',
        variants: ['original', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      {
        id: 'travis',
        label: 'Travis',
        icon: 'travis',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'vagrant', label: 'Vagrant', icon: 'vagrant', variants: ['plain', 'plain-wordmark'] },
    ],
  },
  {
    type: 'testing',
    label: 'Testing',
    color: 'from-teal-500 to-cyan-500',
    techStacks: [
      {
        id: 'browserstack',
        label: 'Browserstack',
        icon: 'browserstack',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'codecov', label: 'Codecov', icon: 'codecov', variants: ['plain'] },
      {
        id: 'cucumber',
        label: 'Cucumber',
        icon: 'cucumber',
        variants: ['plain', 'plain-wordmark'],
      },
      {
        id: 'cypressio',
        label: 'Cypressio',
        icon: 'cypressio',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      {
        id: 'gatling',
        label: 'Gatling',
        icon: 'gatling',
        variants: ['original', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      {
        id: 'jasmine',
        label: 'Jasmine',
        icon: 'jasmine',
        variants: ['original', 'original-wordmark'],
      },
      { id: 'jest', label: 'Jest', icon: 'jest', variants: ['plain'] },
      {
        id: 'junit',
        label: 'Junit',
        icon: 'junit',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'k6', label: 'K6', icon: 'k6', variants: ['original'] },
      {
        id: 'karatelabs',
        label: 'Karatelabs',
        icon: 'karatelabs',
        variants: ['plain', 'plain-wordmark'],
      },
      { id: 'karma', label: 'Karma', icon: 'karma', variants: ['plain'] },
      { id: 'mocha', label: 'Mocha', icon: 'mocha', variants: ['plain'] },
      { id: 'playwright', label: 'Playwright', icon: 'playwright', variants: ['plain'] },
      {
        id: 'protractor',
        label: 'Protractor',
        icon: 'protractor',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'puppeteer', label: 'Puppeteer', icon: 'puppeteer', variants: ['plain'] },
      { id: 'pytest', label: 'Pytest', icon: 'pytest', variants: ['plain', 'plain-wordmark'] },
      { id: 'qodana', label: 'Qodana', icon: 'qodana', variants: ['plain', 'plain-wordmark'] },
      { id: 'qtest', label: 'Qtest', icon: 'qtest', variants: ['original', 'original-wordmark'] },
      {
        id: 'rspec',
        label: 'Rspec',
        icon: 'rspec',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'selenium', label: 'Selenium', icon: 'selenium', variants: ['original'] },
      { id: 'vitest', label: 'Vitest', icon: 'vitest', variants: ['plain'] },
    ],
  },
  {
    type: 'api',
    label: 'API & Web3',
    color: 'from-indigo-500 to-purple-500',
    techStacks: [
      {
        id: 'algolia',
        label: 'Algolia',
        icon: 'algolia',
        variants: ['original', 'original-wordmark'],
      },
      {
        id: 'apollographql',
        label: 'Apollographql',
        icon: 'apollographql',
        variants: ['original', 'original-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'axios', label: 'Axios', icon: 'axios', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'discordjs',
        label: 'Discord.js',
        icon: 'discordjs',
        variants: ['plain', 'plain-wordmark'],
      },
      { id: 'fastapi', label: 'Fastapi', icon: 'fastapi', variants: ['plain', 'plain-wordmark'] },
      { id: 'graphql', label: 'Graphql', icon: 'graphql', variants: ['plain', 'plain-wordmark'] },
      { id: 'grpc', label: 'Grpc', icon: 'grpc', variants: ['plain'] },
      { id: 'hardhat', label: 'Hardhat', icon: 'hardhat', variants: ['plain', 'plain-wordmark'] },
      { id: 'hoppscotch', label: 'Hoppscotch', icon: 'hoppscotch', variants: ['plain'] },
      {
        id: 'insomnia',
        label: 'Insomnia',
        icon: 'insomnia',
        variants: ['plain', 'plain-wordmark'],
      },
      { id: 'ngrok', label: 'Ngrok', icon: 'ngrok', variants: ['original', 'line'] },
      { id: 'oauth', label: 'Oauth', icon: 'oauth', variants: ['plain'] },
      { id: 'okta', label: 'Okta', icon: 'okta', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'openapi',
        label: 'Openapi',
        icon: 'openapi',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'ory', label: 'Ory', icon: 'ory', variants: ['original', 'original-wordmark'] },
      {
        id: 'passport',
        label: 'Passport',
        icon: 'passport',
        variants: ['plain', 'original-wordmark'],
      },
      { id: 'polygon', label: 'Polygon', icon: 'polygon', variants: ['plain', 'plain-wordmark'] },
      { id: 'postman', label: 'Postman', icon: 'postman', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'socketio',
        label: 'Socketio',
        icon: 'socketio',
        variants: ['original', 'original-wordmark'],
      },
      { id: 'swagger', label: 'Swagger', icon: 'swagger', variants: ['plain', 'plain-wordmark'] },
      { id: 'trpc', label: 'Trpc', icon: 'trpc', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'twilio',
        label: 'Twilio',
        icon: 'twilio',
        variants: ['original', 'original-wordmark'],
      },
      { id: 'web3js', label: 'Web3.js', icon: 'web3js', variants: ['plain'] },
    ],
  },
  {
    type: 'mobile',
    label: 'Mobile',
    color: 'from-purple-500 to-indigo-500',
    techStacks: [
      {
        id: 'appcelerator',
        label: 'Appcelerator',
        icon: 'appcelerator',
        variants: ['original', 'plain-wordmark'],
      },
      { id: 'apple', label: 'Apple', icon: 'apple', variants: ['original'] },
      {
        id: 'capacitor',
        label: 'Capacitor',
        icon: 'capacitor',
        variants: ['plain', 'plain-wordmark'],
      },
      {
        id: 'expo',
        label: 'Expo',
        icon: 'expo',
        variants: ['original', 'original-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'flutter', label: 'Flutter', icon: 'flutter', variants: ['plain'] },
      { id: 'ionic', label: 'Ionic', icon: 'ionic', variants: ['original', 'original-wordmark'] },
      {
        id: 'jetpackcompose',
        label: 'Jetpackcompose',
        icon: 'jetpackcompose',
        variants: ['plain-wordmark', 'plain', 'line', 'line-wordmark'],
      },
      {
        id: 'reactnative',
        label: 'Reactnative',
        icon: 'reactnative',
        variants: ['original', 'original-wordmark'],
      },
      { id: 'titaniumsdk', label: 'Titaniumsdk', icon: 'titaniumsdk', variants: ['original'] },
      {
        id: 'xamarin',
        label: 'Xamarin',
        icon: 'xamarin',
        variants: ['original', 'original-wordmark'],
      },
    ],
  },
  {
    type: 'game',
    label: 'Game & Graphics',
    color: 'from-red-500 to-pink-500',
    techStacks: [
      { id: 'aframe', label: 'Aframe', icon: 'aframe', variants: ['original-wordmark', 'plain'] },
      {
        id: 'babylonjs',
        label: 'Babylon.js',
        icon: 'babylonjs',
        variants: ['plain', 'plain-wordmark'],
      },
      {
        id: 'bevyengine',
        label: 'Bevyengine',
        icon: 'bevyengine',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'fusion', label: 'Fusion', icon: 'fusion', variants: ['plain'] },
      { id: 'gazebo', label: 'Gazebo', icon: 'gazebo', variants: ['plain', 'plain-wordmark'] },
      { id: 'godot', label: 'Godot', icon: 'godot', variants: ['plain', 'plain-wordmark'] },
      { id: 'libgdx', label: 'Libgdx', icon: 'libgdx', variants: ['plain', 'line'] },
      { id: 'love2d', label: 'Love2d', icon: 'love2d', variants: ['plain', 'line'] },
      {
        id: 'monogame',
        label: 'Monogame',
        icon: 'monogame',
        variants: ['original', 'line', 'line-wordmark'],
      },
      { id: 'openal', label: 'Openal', icon: 'openal', variants: ['plain'] },
      { id: 'opencl', label: 'Opencl', icon: 'opencl', variants: ['plain', 'line'] },
      { id: 'opengl', label: 'Opengl', icon: 'opengl', variants: ['plain'] },
      { id: 'p5js', label: 'P5.js', icon: 'p5js', variants: ['original'] },
      { id: 'photonengine', label: 'Photonengine', icon: 'photonengine', variants: ['plain'] },
      { id: 'pixijs', label: 'Pixi.js', icon: 'pixijs', variants: ['plain', 'plain-wordmark'] },
      { id: 'renpy', label: 'Renpy', icon: 'renpy', variants: ['plain'] },
      { id: 'sdl', label: 'Sdl', icon: 'sdl', variants: ['plain'] },
      {
        id: 'shotgrid',
        label: 'Shotgrid',
        icon: 'shotgrid',
        variants: ['plain', 'original-wordmark'],
      },
      {
        id: 'sourceengine',
        label: 'Sourceengine',
        icon: 'sourceengine',
        variants: ['plain', 'plain-wordmark'],
      },
      {
        id: 'threejs',
        label: 'Three.js',
        icon: 'threejs',
        variants: ['original', 'original-wordmark'],
      },
      {
        id: 'unity',
        label: 'Unity',
        icon: 'unity',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      {
        id: 'unrealengine',
        label: 'Unrealengine',
        icon: 'unrealengine',
        variants: ['original', 'original-wordmark'],
      },
      { id: 'vulkan', label: 'Vulkan', icon: 'vulkan', variants: ['original', 'line'] },
      {
        id: 'webgpu',
        label: 'Webgpu',
        icon: 'webgpu',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
    ],
  },
  {
    type: 'ide',
    label: 'IDE & Editor',
    color: 'from-yellow-500 to-orange-500',
    techStacks: [
      {
        id: 'androidstudio',
        label: 'Androidstudio',
        icon: 'androidstudio',
        variants: ['plain', 'plain-wordmark'],
      },
      { id: 'atom', label: 'Atom', icon: 'atom', variants: ['original', 'original-wordmark'] },
      { id: 'clion', label: 'Clion', icon: 'clion', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'codepen',
        label: 'Codepen',
        icon: 'codepen',
        variants: ['original', 'original-wordmark', 'line', 'line-wordmark'],
      },
      {
        id: 'datagrip',
        label: 'Datagrip',
        icon: 'datagrip',
        variants: ['plain', 'plain-wordmark'],
      },
      {
        id: 'dataspell',
        label: 'Dataspell',
        icon: 'dataspell',
        variants: ['plain', 'plain-wordmark'],
      },
      { id: 'dreamweaver', label: 'Dreamweaver', icon: 'dreamweaver', variants: ['plain', 'line'] },
      { id: 'eclipse', label: 'Eclipse', icon: 'eclipse', variants: ['plain-wordmark', 'plain'] },
      { id: 'emacs', label: 'Emacs', icon: 'emacs', variants: ['original'] },
      {
        id: 'githubcodespaces',
        label: 'Githubcodespaces',
        icon: 'githubcodespaces',
        variants: ['plain'],
      },
      { id: 'gitpod', label: 'Gitpod', icon: 'gitpod', variants: ['plain', 'plain-wordmark'] },
      { id: 'goland', label: 'Goland', icon: 'goland', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'intellij',
        label: 'Intellij',
        icon: 'intellij',
        variants: ['plain', 'plain-wordmark'],
      },
      { id: 'jetbrains', label: 'Jetbrains', icon: 'jetbrains', variants: ['plain'] },
      { id: 'nano', label: 'Nano', icon: 'nano', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'neovim',
        label: 'Neovim',
        icon: 'neovim',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      {
        id: 'netbeans',
        label: 'Netbeans',
        icon: 'netbeans',
        variants: ['plain', 'plain-wordmark'],
      },
      {
        id: 'phpstorm',
        label: 'Phpstorm',
        icon: 'phpstorm',
        variants: ['plain', 'plain-wordmark'],
      },
      {
        id: 'pulsar',
        label: 'Pulsar',
        icon: 'pulsar',
        variants: ['original', 'original-wordmark'],
      },
      { id: 'pycharm', label: 'Pycharm', icon: 'pycharm', variants: ['plain', 'plain-wordmark'] },
      { id: 'radstudio', label: 'Radstudio', icon: 'radstudio', variants: ['plain'] },
      { id: 'replit', label: 'Replit', icon: 'replit', variants: ['original', 'plain-wordmark'] },
      { id: 'rider', label: 'Rider', icon: 'rider', variants: ['plain', 'plain-wordmark'] },
      { id: 'rstudio', label: 'Rstudio', icon: 'rstudio', variants: ['plain'] },
      {
        id: 'rubymine',
        label: 'Rubymine',
        icon: 'rubymine',
        variants: ['plain', 'plain-wordmark'],
      },
      { id: 'spyder', label: 'Spyder', icon: 'spyder', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'stackblitz',
        label: 'Stackblitz',
        icon: 'stackblitz',
        variants: ['original', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'vim', label: 'Vim', icon: 'vim', variants: ['plain'] },
      {
        id: 'visualstudio',
        label: 'Visualstudio',
        icon: 'visualstudio',
        variants: ['plain', 'line'],
      },
      { id: 'vscode', label: 'Vscode', icon: 'vscode', variants: ['plain', 'plain-wordmark'] },
      { id: 'vscodium', label: 'Vscodium', icon: 'vscodium', variants: ['plain'] },
      {
        id: 'webstorm',
        label: 'Webstorm',
        icon: 'webstorm',
        variants: ['plain', 'plain-wordmark'],
      },
      { id: 'xcode', label: 'Xcode', icon: 'xcode', variants: ['plain'] },
    ],
  },
  {
    type: 'buildtools',
    label: 'Build Tools',
    color: 'from-lime-500 to-green-500',
    techStacks: [
      { id: 'babel', label: 'Babel', icon: 'babel', variants: ['plain'] },
      { id: 'bazel', label: 'Bazel', icon: 'bazel', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'bower',
        label: 'Bower',
        icon: 'bower',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'bun', label: 'Bun', icon: 'bun', variants: ['plain', 'line'] },
      { id: 'cmake', label: 'Cmake', icon: 'cmake', variants: ['plain', 'plain-wordmark'] },
      { id: 'composer', label: 'Composer', icon: 'composer', variants: ['line', 'line-wordmark'] },
      {
        id: 'electron',
        label: 'Electron',
        icon: 'electron',
        variants: ['original', 'original-wordmark'],
      },
      {
        id: 'gradle',
        label: 'Gradle',
        icon: 'gradle',
        variants: ['original', 'original-wordmark'],
      },
      {
        id: 'grunt',
        label: 'Grunt',
        icon: 'grunt',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'gulp', label: 'Gulp', icon: 'gulp', variants: ['plain'] },
      {
        id: 'homebrew',
        label: 'Homebrew',
        icon: 'homebrew',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'hugo', label: 'Hugo', icon: 'hugo', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'jamstack',
        label: 'Jamstack',
        icon: 'jamstack',
        variants: ['original', 'plain-wordmark'],
      },
      { id: 'jekyll', label: 'Jekyll', icon: 'jekyll', variants: ['plain', 'plain-wordmark'] },
      { id: 'maven', label: 'Maven', icon: 'maven', variants: ['plain', 'plain-wordmark'] },
      { id: 'nimble', label: 'Nimble', icon: 'nimble', variants: ['plain'] },
      { id: 'npm', label: 'Npm', icon: 'npm', variants: ['original-wordmark', 'plain'] },
      { id: 'nuget', label: 'Nuget', icon: 'nuget', variants: ['original', 'original-wordmark'] },
      { id: 'pnpm', label: 'Pnpm', icon: 'pnpm', variants: ['plain', 'plain-wordmark'] },
      { id: 'poetry', label: 'Poetry', icon: 'poetry', variants: ['plain'] },
      { id: 'pypi', label: 'Pypi', icon: 'pypi', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'rollup',
        label: 'Rollup',
        icon: 'rollup',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'spack', label: 'Spack', icon: 'spack', variants: ['plain'] },
      { id: 'tauri', label: 'Tauri', icon: 'tauri', variants: ['plain', 'plain-wordmark'] },
      { id: 'vite', label: 'Vite', icon: 'vite', variants: ['original', 'original-wordmark'] },
      { id: 'vitejs', label: 'Vite.js', icon: 'vitejs', variants: ['plain'] },
      { id: 'webpack', label: 'Webpack', icon: 'webpack', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'yarn',
        label: 'Yarn',
        icon: 'yarn',
        variants: ['original', 'original-wordmark', 'line', 'line-wordmark'],
      },
    ],
  },
  {
    type: 'os',
    label: 'Operating System',
    color: 'from-slate-500 to-gray-500',
    techStacks: [
      {
        id: 'almalinux',
        label: 'Almalinux',
        icon: 'almalinux',
        variants: ['plain', 'plain-wordmark'],
      },
      { id: 'android', label: 'Android', icon: 'android', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'archlinux',
        label: 'Archlinux',
        icon: 'archlinux',
        variants: ['plain', 'plain-wordmark'],
      },
      {
        id: 'artixlinux',
        label: 'Artixlinux',
        icon: 'artixlinux',
        variants: ['plain', 'plain-wordmark'],
      },
      { id: 'centos', label: 'Centos', icon: 'centos', variants: ['plain', 'plain-wordmark'] },
      { id: 'debian', label: 'Debian', icon: 'debian', variants: ['plain', 'plain-wordmark'] },
      { id: 'fedora', label: 'Fedora', icon: 'fedora', variants: ['plain'] },
      {
        id: 'gentoo',
        label: 'Gentoo',
        icon: 'gentoo',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      {
        id: 'kalilinux',
        label: 'Kalilinux',
        icon: 'kalilinux',
        variants: ['original', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'kdeneon', label: 'Kdeneon', icon: 'kdeneon', variants: ['plain'] },
      { id: 'linux', label: 'Linux', icon: 'linux', variants: ['plain'] },
      {
        id: 'linuxmint',
        label: 'Linuxmint',
        icon: 'linuxmint',
        variants: ['plain', 'plain-wordmark'],
      },
      { id: 'msdos', label: 'Msdos', icon: 'msdos', variants: ['plain', 'line'] },
      { id: 'nixos', label: 'Nixos', icon: 'nixos', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'opensuse',
        label: 'Opensuse',
        icon: 'opensuse',
        variants: ['original', 'original-wordmark'],
      },
      {
        id: 'pfsense',
        label: 'Pfsense',
        icon: 'pfsense',
        variants: ['original', 'original-wordmark'],
      },
      { id: 'redhat', label: 'Redhat', icon: 'redhat', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'rockylinux',
        label: 'Rockylinux',
        icon: 'rockylinux',
        variants: ['original', 'plain-wordmark'],
      },
      { id: 'ubuntu', label: 'Ubuntu', icon: 'ubuntu', variants: ['plain', 'plain-wordmark'] },
      { id: 'unix', label: 'Unix', icon: 'unix', variants: ['original'] },
      {
        id: 'windows11',
        label: 'Windows11',
        icon: 'windows11',
        variants: ['original', 'original-wordmark'],
      },
      {
        id: 'windows8',
        label: 'Windows8',
        icon: 'windows8',
        variants: ['original', 'original-wordmark'],
      },
      { id: 'yunohost', label: 'Yunohost', icon: 'yunohost', variants: ['plain'] },
    ],
  },
  {
    type: 'design',
    label: 'Design & Creative',
    color: 'from-fuchsia-500 to-pink-500',
    techStacks: [
      { id: 'aftereffects', label: 'Aftereffects', icon: 'aftereffects', variants: ['plain'] },
      { id: 'behance', label: 'Behance', icon: 'behance', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'blender',
        label: 'Blender',
        icon: 'blender',
        variants: ['original', 'original-wordmark'],
      },
      { id: 'canva', label: 'Canva', icon: 'canva', variants: ['original'] },
      { id: 'figma', label: 'Figma', icon: 'figma', variants: ['plain'] },
      {
        id: 'gimp',
        label: 'Gimp',
        icon: 'gimp',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'illustrator', label: 'Illustrator', icon: 'illustrator', variants: ['plain', 'line'] },
      {
        id: 'inkscape',
        label: 'Inkscape',
        icon: 'inkscape',
        variants: ['plain', 'plain-wordmark'],
      },
      { id: 'maya', label: 'Maya', icon: 'maya', variants: ['plain', 'plain-wordmark'] },
      { id: 'photoshop', label: 'Photoshop', icon: 'photoshop', variants: ['plain', 'line'] },
      { id: 'premierepro', label: 'Premierepro', icon: 'premierepro', variants: ['plain'] },
      {
        id: 'sketch',
        label: 'Sketch',
        icon: 'sketch',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'threedsmax', label: 'Threedsmax', icon: 'threedsmax', variants: ['plain'] },
      { id: 'xd', label: 'Xd', icon: 'xd', variants: ['plain', 'line'] },
    ],
  },
  {
    type: 'datascience',
    label: 'Data Science & ML',
    color: 'from-violet-500 to-purple-500',
    techStacks: [
      {
        id: 'anaconda',
        label: 'Anaconda',
        icon: 'anaconda',
        variants: ['original', 'original-wordmark'],
      },
      {
        id: 'apachespark',
        label: 'Apachespark',
        icon: 'apachespark',
        variants: ['original', 'plain-wordmark'],
      },
      { id: 'googlecolab', label: 'Googlecolab', icon: 'googlecolab', variants: ['plain'] },
      { id: 'hadoop', label: 'Hadoop', icon: 'hadoop', variants: ['plain', 'plain-wordmark'] },
      { id: 'jupyter', label: 'Jupyter', icon: 'jupyter', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'kaggle',
        label: 'Kaggle',
        icon: 'kaggle',
        variants: ['original', 'original-wordmark'],
      },
      {
        id: 'kaldi',
        label: 'Kaldi',
        icon: 'kaldi',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      {
        id: 'keras',
        label: 'Keras',
        icon: 'keras',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      {
        id: 'matplotlib',
        label: 'Matplotlib',
        icon: 'matplotlib',
        variants: ['plain', 'plain-wordmark'],
      },
      { id: 'minitab', label: 'Minitab', icon: 'minitab', variants: ['plain'] },
      {
        id: 'networkx',
        label: 'Networkx',
        icon: 'networkx',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      {
        id: 'numpy',
        label: 'Numpy',
        icon: 'numpy',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'opencv', label: 'Opencv', icon: 'opencv', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'pandas',
        label: 'Pandas',
        icon: 'pandas',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'plotly', label: 'Plotly', icon: 'plotly', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'pytorch',
        label: 'Pytorch',
        icon: 'pytorch',
        variants: ['original', 'plain-wordmark'],
      },
      { id: 'scikitlearn', label: 'Scikitlearn', icon: 'scikitlearn', variants: ['plain', 'line'] },
      { id: 'spss', label: 'Spss', icon: 'spss', variants: ['plain'] },
      {
        id: 'streamlit',
        label: 'Streamlit',
        icon: 'streamlit',
        variants: ['plain', 'plain-wordmark'],
      },
      {
        id: 'tensorflow',
        label: 'Tensorflow',
        icon: 'tensorflow',
        variants: ['original', 'original-wordmark', 'line', 'line-wordmark'],
      },
    ],
  },
  {
    type: 'hardware',
    label: 'Hardware & IoT',
    color: 'from-amber-500 to-orange-500',
    techStacks: [
      { id: 'aarch64', label: 'Aarch64', icon: 'aarch64', variants: ['plain', 'line'] },
      { id: 'arduino', label: 'Arduino', icon: 'arduino', variants: ['plain', 'plain-wordmark'] },
      { id: 'gcc', label: 'Gcc', icon: 'gcc', variants: ['plain', 'line'] },
      { id: 'qt', label: 'Qt', icon: 'qt', variants: ['original'] },
      {
        id: 'raspberrypi',
        label: 'Raspberrypi',
        icon: 'raspberrypi',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'ros', label: 'Ros', icon: 'ros', variants: ['original', 'original-wordmark'] },
    ],
  },
  {
    type: 'browser',
    label: 'Browser',
    color: 'from-sky-500 to-blue-500',
    techStacks: [
      { id: 'chrome', label: 'Chrome', icon: 'chrome', variants: ['plain', 'plain-wordmark'] },
      { id: 'firefox', label: 'Firefox', icon: 'firefox', variants: ['plain', 'plain-wordmark'] },
      { id: 'ie10', label: 'Ie10', icon: 'ie10', variants: ['original'] },
      { id: 'opera', label: 'Opera', icon: 'opera', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'safari',
        label: 'Safari',
        icon: 'safari',
        variants: ['plain', 'plain-wordmark', 'line-wordmark', 'line'],
      },
    ],
  },
  {
    type: 'social',
    label: 'Social & Collaboration',
    color: 'from-rose-500 to-pink-500',
    techStacks: [
      {
        id: 'confluence',
        label: 'Confluence',
        icon: 'confluence',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'facebook', label: 'Facebook', icon: 'facebook', variants: ['plain'] },
      { id: 'gitter', label: 'Gitter', icon: 'gitter', variants: ['plain', 'plain-wordmark'] },
      { id: 'ifttt', label: 'Ifttt', icon: 'ifttt', variants: ['original'] },
      { id: 'jira', label: 'Jira', icon: 'jira', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'jiraalign',
        label: 'Jiraalign',
        icon: 'jiraalign',
        variants: ['plain', 'plain-wordmark'],
      },
      {
        id: 'linkedin',
        label: 'Linkedin',
        icon: 'linkedin',
        variants: ['plain', 'plain-wordmark'],
      },
      {
        id: 'mattermost',
        label: 'Mattermost',
        icon: 'mattermost',
        variants: ['original', 'original-wordmark'],
      },
      { id: 'notion', label: 'Notion', icon: 'notion', variants: ['plain', 'line'] },
      { id: 'slack', label: 'Slack', icon: 'slack', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'trello',
        label: 'Trello',
        icon: 'trello',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'twitter', label: 'Twitter', icon: 'twitter', variants: ['original'] },
    ],
  },
  {
    type: 'documentation',
    label: 'Documentation',
    color: 'from-emerald-500 to-teal-500',
    techStacks: [
      {
        id: 'devicon',
        label: 'Devicon',
        icon: 'devicon',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'json', label: 'Json', icon: 'json', variants: ['plain'] },
      { id: 'latex', label: 'Latex', icon: 'latex', variants: ['original'] },
      { id: 'markdown', label: 'Markdown', icon: 'markdown', variants: ['original'] },
      { id: 'norg', label: 'Norg', icon: 'norg', variants: ['plain'] },
      {
        id: 'readthedocs',
        label: 'Readthedocs',
        icon: 'readthedocs',
        variants: ['original', 'original-wordmark', 'line'],
      },
      {
        id: 'storybook',
        label: 'Storybook',
        icon: 'storybook',
        variants: ['plain', 'plain-wordmark'],
      },
      { id: 'tex', label: 'Tex', icon: 'tex', variants: ['original'] },
      { id: 'xml', label: 'Xml', icon: 'xml', variants: ['plain', 'line'] },
      { id: 'yaml', label: 'Yaml', icon: 'yaml', variants: ['plain'] },
    ],
  },
  {
    type: 'other',
    label: 'Other',
    color: 'from-gray-500 to-slate-500',
    techStacks: [
      { id: 'ansys', label: 'Ansys', icon: 'ansys', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'entityframeworkcore',
        label: 'Entityframeworkcore',
        icon: 'entityframeworkcore',
        variants: ['plain', 'line'],
      },
      { id: 'glitch', label: 'Glitch', icon: 'glitch', variants: ['plain'] },
      { id: 'google', label: 'Google', icon: 'google', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'leetcode',
        label: 'Leetcode',
        icon: 'leetcode',
        variants: ['plain', 'line', 'plain-wordmark', 'line-wordmark'],
      },
      { id: 'mapbox', label: 'Mapbox', icon: 'mapbox', variants: ['original'] },
      { id: 'npss', label: 'Npss', icon: 'npss', variants: ['plain'] },
      { id: 'ohmyzsh', label: 'Ohmyzsh', icon: 'ohmyzsh', variants: ['plain'] },
      { id: 'pyscript', label: 'Pyscript', icon: 'pyscript', variants: ['plain-wordmark'] },
      { id: 'sema', label: 'Sema', icon: 'sema', variants: ['original', 'original-wordmark'] },
      {
        id: 'stackoverflow',
        label: 'Stackoverflow',
        icon: 'stackoverflow',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
      { id: 'stata', label: 'Stata', icon: 'stata', variants: ['original-wordmark'] },
      {
        id: 'thealgorithms',
        label: 'Thealgorithms',
        icon: 'thealgorithms',
        variants: ['plain', 'plain-wordmark'],
      },
      { id: 'turbo', label: 'Turbo', icon: 'turbo', variants: ['original', 'plain-wordmark'] },
      {
        id: 'unifiedmodelinglanguage',
        label: 'Unifiedmodelinglanguage',
        icon: 'unifiedmodelinglanguage',
        variants: ['plain', 'plain-wordmark'],
      },
      { id: 'v8', label: 'V8', icon: 'v8', variants: ['plain'] },
      { id: 'weblate', label: 'Weblate', icon: 'weblate', variants: ['plain', 'plain-wordmark'] },
      {
        id: 'zsh',
        label: 'Zsh',
        icon: 'zsh',
        variants: ['plain', 'plain-wordmark', 'line', 'line-wordmark'],
      },
    ],
  },
];
